<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net472</TargetFramework><LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../master/MasterConsole.Protocol/MasterConsole.Protocol.csproj" />
    <Compile Include="../../master/MasterConsole/Services/HandleService.cs" Link="HandleService.cs" />
    <Compile Include="../../master/MasterConsole/Services/RemoteRobotLink.cs" Link="RemoteRobotLink.cs" />
    <Compile Include="../../master/MasterConsole/Services/IRobotLink.cs" Link="IRobotLink.cs" />
  </ItemGroup>
</Project>
